apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: guestbook-ui
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`guestbook.local`)
      kind: Rule
      services:
        - name: guestbook-ui
          port: 80
